#spring.application.name=springboot-service-store
server:
  port: 8082
spring:
  application:
    name: service-store
  #mvc:
   # pathmatch:
    #  matching-strategy: ANT_PATH_MATCHER
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
